"""Add is_draft to food

Revision ID: 0481f4cf076e
Revises: 9695834bc820
Create Date: 2026-02-22 00:51:48.834744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0481f4cf076e'
down_revision: Union[str, None] = '9695834bc820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('is_draft', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foods', 'is_draft')
    # ### end Alembic commands ###
