"""add_food_portions_table

Revision ID: 0c06fd395172
Revises: 0d6e076dfac9
Create Date: 2026-02-23 18:46:23.887722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c06fd395172'
down_revision: Union[str, None] = '0d6e076dfac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_portions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weight_g', sa.Float(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_portions_food_id'), 'food_portions', ['food_id'], unique=False)
    op.create_index(op.f('ix_food_portions_id'), 'food_portions', ['id'], unique=False)
    op.add_column('recipe_ingredients', sa.Column('food_portion_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipe_ingredients', 'food_portions', ['food_portion_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe_ingredients', type_='foreignkey')
    op.drop_column('recipe_ingredients', 'food_portion_id')
    op.drop_index(op.f('ix_food_portions_id'), table_name='food_portions')
    op.drop_index(op.f('ix_food_portions_food_id'), table_name='food_portions')
    op.drop_table('food_portions')
    # ### end Alembic commands ###
