"""Add density and portion weight to foods

Revision ID: 0d6e076dfac9
Revises: 7af4e955e9b0
Create Date: 2026-02-22 19:41:37.445965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d6e076dfac9'
down_revision: Union[str, None] = '7af4e955e9b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('density', sa.Float(), nullable=False, server_default='1.0'))
    op.add_column('foods', sa.Column('portion_weight_g', sa.Float(), nullable=False, server_default='100.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foods', 'portion_weight_g')
    op.drop_column('foods', 'density')
    # ### end Alembic commands ###
