"""Add shopping list models if needed

Revision ID: 2b9cd9964a9a
Revises: c5da6e839464
Create Date: 2026-02-21 16:29:59.710602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b9cd9964a9a'
down_revision: Union[str, None] = 'c5da6e839464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
