"""Add raw quantity and unit to recipe ingredients

Revision ID: 7af4e955e9b0
Revises: b75ca312e783
Create Date: 2026-02-22 16:44:59.210371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af4e955e9b0'
down_revision: Union[str, None] = 'b75ca312e783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_ingredients', sa.Column('raw_quantity', sa.Float(), nullable=True))
    op.add_column('recipe_ingredients', sa.Column('raw_unit', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_ingredients', 'raw_unit')
    op.drop_column('recipe_ingredients', 'raw_quantity')
    # ### end Alembic commands ###
