"""Add volumetric nutrition fields

Revision ID: b75ca312e783
Revises: 0481f4cf076e
Create Date: 2026-02-22 09:11:26.405093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b75ca312e783'
down_revision: Union[str, None] = '0481f4cf076e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_plans', sa.Column('target_volume_g', sa.Float(), nullable=True))
    op.add_column('meals', sa.Column('target_volume_g', sa.Float(), nullable=True))
    op.add_column('recipe_ingredients', sa.Column('state', sa.Enum('RAW', 'COOKED', name='ingredientstate'), nullable=True))
    op.add_column('users', sa.Column('target_weekly_kcal', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'target_weekly_kcal')
    op.drop_column('recipe_ingredients', 'state')
    op.drop_column('meals', 'target_volume_g')
    op.drop_column('meal_plans', 'target_volume_g')
    # ### end Alembic commands ###
